(******************************************************************************)
(*                                                                            *)
(*          Parts Closure: Verified Bootstrap-Manufacturable Subset           *)
(*                                                                            *)
(*     Closure of a parts list under the make-from relation. The closure      *)
(*     is the largest subset where every part can be manufactured from        *)
(*     some other parts in the subset using verified machines.                *)
(*                                                                            *)
(*     "Every monotone map has a fixed point."                                *)
(*     - Alfred Tarski, 1955                                                  *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: May 8, 2026                                                      *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
